# This file was generated by pkgs.mastodon.updateScript.
{ fetchgit, applyPatches }: let
  src = fetchgit {
    url = "https://github.com/mastodon/mastodon.git";
    rev = "v4.0.0rc3";
    sha256 = "0mqwhw6qr0hxhyz1gznqp568q9g7z0fzy7l0r311hclskq34yz8y";
  };
in applyPatches {
  inherit src;
  patches = [];
}
